### ISSUE TITLE
Fix support for python2.6

### ISSUE THREAD

**Issue by portante** [portante/pycscope#20]
It seems that pycscope-1.2.1.tar.gz generates the following error on install for a python2.6 environment:

 File "setup.py", line 5, in <module>
    from pycscope import **version**
  File "/my_current_directory/pycscope-1.2.1/pycscope/**init**.py", line 597, in <module>
    testlist_comp = (symbol.testlist_comp, symbol.listmaker)
AttributeError: 'module' object has no attribute 'testlist_comp'

**Comment by prernasaxena** [comment]
Hi @portante ,
Thanks. https://github.com/portante/pycscope/commit/de8f7584cde3150bc3c655499f15f11883455d9e
does fix the install for Python 2.6.
I was wondering if you might want to create a new release ? The current stable release posted on python.org site for this plugin (https://pypi.python.org/pypi/pycscope/) does not work for Python 2.6 users.

**Comment by portante** [comment]
@prernasaxena, I do plan to create a new release.  I am working on reliable unit tests under Travis-CI first, and then I'll release all this.  It will take some time.  Sorry!

**Comment by portante** [comment]
Won't fix. Last Python 2 is now 2.7.  Please open a new bug for problems under 2.7 environments.
