### ISSUE TITLE
pycscope is incompatible with cscope on windows

### ISSUE THREAD

**Issue by skywind3000** [portante/pycscope#30]
Reproduce:

```
E:\Lab\casuald\lib>pycscope -R
E:\Lab\casuald\lib>cscope -dl -f cscope.out
cscope: cannot read trailer offset from file cscope.out
```

Expect:
cscope should load "cscope.out" correctly on windows, just like on linux

Result:
cscope report an error: "cscope: cannot read trailer offset from file cscope.out"

Version:
cscope.exe: 15.8a (from: [cscope-win32](http://code.google.com/p/cscope-win32))
pycscope: 1.2.1 (installed by pip)
Windows: Windows 7
Python: 2.7.12 32bits

**Comment by portante** [comment]
None of this work has been done on Windows in the past.  If you find a way to make it work on Windows, it would be great to have a patch for that.

**Comment by skywind3000** [comment]
actually, I figure out my self, 
After upgrading cscope from 15.8a to 15.8b, pycscope can work with cscope on windows now !!

**Comment by portante** [comment]
Thanks for finding that out and recording it here.

**Comment by Cloudprogram** [comment]
> actually, I figure out my self,
> After upgrading cscope from 15.8a to 15.8b, pycscope can work with cscope on windows now !!
> without any modification

where can find 15.8b ???

**Comment by skywind3000** [comment]
Despite that cscope's homepages hasn't been updated for a long time, but you can find `15.8b` and even `15.9` now the `Files` section in sourceforge's cscope project page.

https://sourceforge.net/projects/cscope/files/

**Comment by Cloudprogram** [comment]
> Despite that cscope's homepages hasn't been updated for a long time, but you can find `15.8b` and even `15.9` now the `Files` section in sourceforge's cscope project page.
> 
> https://sourceforge.net/projects/cscope/files/

but it‘s for linux，i want to find the one in windows。
There’s error in version cscope-15.8a-win64rev1-static.zip 
https://code.google.com/archive/p/cscope-win32/downloads。
maybe 15.8b have fixed the bug。
what you use to browse the linux kernal？
vim + cscope？sourceinsight？

**Comment by skywind3000** [comment]
scitool understand

**Comment by Cloudprogram** [comment]
where can i find the cscope for Windows above 15.8a？




| |
李坤
邮箱：googleapple1@163.com
|

签名由 网易邮箱大师 定制

On 07/15/2019 11:55, Linwei wrote:

scitool understand

**Comment by skywind3000** [comment]
compile your self

**Comment by Cloudprogram** [comment]
> > Despite that cscope's homepages hasn't been updated for a long time, but you can find `15.8b` and even `15.9` now the `Files` section in sourceforge's cscope project page.
> > https://sourceforge.net/projects/cscope/files/
> 
> but it‘s for linux，i want to find the one in windows。 There’s error in version cscope-15.8a-win64rev1-static.zip [https://code.google.com/archive/p/cscope-win32/downloads。](https://code.google.com/archive/p/cscope-win32/downloads%E3%80%82) maybe 15.8b have fixed the bug。 what you use to browse the linux kernal？ vim + cscope？sourceinsight？

https://code.google.com/archive/p/cscope-win32/downloads
i use cscope-win32 with cscope.out which is created in ubuntu,it also get the error "cannot read trailer offset from file
cscope.out",windows and linux version is the same as cscope: version 15.8a.
suddenly i create cscope.out with cscope-win32 ,and it works well,but it can't support -q.

```shell
cscope -Rbkq -i ./cscope.files
cscope: cannot create inverted index; ignoring -q option
cscope: removed files ncscope.in.out and ncscope.po.out
```
